# -*- coding: utf-8 -*-
"""SmartCropRecommendationSystem.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wlnr8IDLW2fHvQN3N-WXtHZY3iESzmdV

AI for Sustainability: Smart Crop Recommendation System This project addresses SDG 2 (Zero Hunger) and SDG 12 (Responsible Consumption) by using Machine Learning to recommend the most suitable crops for specific soil and environmental conditions. This ensures higher yields for farmers and reduces the waste of water and fertilizers.# New Section

Import necessary libraries for data processing, machine learning, and visualization
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, accuracy_score

"""Data Loading and Initial Exploration"""

# Load the dataset
df = pd.read_csv('Crop_recommendation.csv')

# View the first 5 rows
print(df.head())

# Check for missing values and data types
df.info()

# See how many types of crops are in the dataset
print("Crops available:", df['label'].unique())

# Define Features and Target
X = df.drop('label', axis=1)
y = df['label']

# Split data: 80% for training, 20% for testing
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize the model
model = RandomForestClassifier(n_estimators=100, random_state=42)

# Train the model
model.fit(X_train, y_train)

# Make predictions
y_pred = model.predict(X_test)

# Calculate accuracy
print(f"Model Accuracy: {accuracy_score(y_test, y_pred) * 100:.2f}%")

# Detailed Report
print(classification_report(y_test, y_pred))

def recommend_crop(n, p, k, temp, humidity, ph, rainfall):
    features = pd.DataFrame([[n, p, k, temp, humidity, ph, rainfall]],
                             columns=X_train.columns) # Use the training feature names
    prediction = model.predict(features)
    return prediction[0]

# Get importance levels from the Random Forest model
importances = model.feature_importances_
feature_names = X.columns

# Plotting
plt.figure(figsize=(10, 6))
sns.barplot(x=importances, y=feature_names, palette='viridis')
plt.title('Which factor is most important for crop selection?')
plt.xlabel('Importance Score')
plt.ylabel('Soil/Environmental Factor')
plt.show()

def sustainability_impact(crop_name):
    # Example data: Standard water/fertilizer needs per crop
    # Aligning with SDG 12: Responsible Consumption
    impact_data = {
        'rice': {'water': 'High', 'fertilizer': 'Medium'},
        'maize': {'water': 'Medium', 'fertilizer': 'High'},
        'chickpea': {'water': 'Low', 'fertilizer': 'Low'}
    }

    info = impact_data.get(crop_name, {'water': 'Unknown', 'fertilizer': 'Unknown'})
    print(f"Sustainability Profile for {crop_name}:")
    print(f"- Water Usage: {info['water']} (Target: Optimization)")
    print(f"- Fertilizer Need: {info['fertilizer']} (Target: Waste Reduction)")

# Add this after your basic print(df.head())
plt.figure(figsize=(10, 8))
sns.heatmap(df.drop('label', axis=1).corr(), annot=True, cmap='coolwarm', fmt='.2f')
plt.title('Correlation between Soil and Environmental Factors')
plt.show()

def recommend_crop_with_confidence(n, p, k, temp, humidity, ph, rainfall):
    features = pd.DataFrame([[n, p, k, temp, humidity, ph, rainfall]],
                             columns=X_train.columns)

    prediction = model.predict(features)[0]
    # Get the probability of the predicted class
    proba = model.predict_proba(features)
    confidence = np.max(proba) * 100

    print(f"--- AI Recommendation ---")
    print(f"Recommended Crop: {prediction}")
    print(f"AI Confidence Level: {confidence:.2f}%")
    return prediction

def sustainability_advisor(crop_name):
    # Mapping more crops to sustainability metrics
    impact_data = {
        'rice': {'water': 'High', 'soil_health': 'Moderate', 'tip': 'Consider Alternate Wetting and Drying (AWD) to save water.'},
        'jute': {'water': 'High', 'soil_health': 'High', 'tip': 'Excellent for crop rotation to improve soil structure.'},
        'coffee': {'water': 'Moderate', 'soil_health': 'High', 'tip': 'Grown best under shade to preserve local biodiversity.'},
        'lentil': {'water': 'Low', 'soil_health': 'Excellent', 'tip': 'Nitrogen-fixing crop; reduces need for chemical fertilizers.'},
        'cotton': {'water': 'High', 'soil_health': 'Low', 'tip': 'Requires careful pest management to avoid excessive chemical use.'}
    }

    info = impact_data.get(crop_name, {'water': 'Variable', 'soil_health': 'Variable', 'tip': 'Consult local agricultural extension for specific eco-tips.'})

    print(f"\n--- Sustainability Advisor (SDG 12 & 13) ---")
    print(f"Selected Crop: {crop_name}")
    print(f"Water Requirement: {info['water']}")
    print(f"Impact on Soil Health: {info['soil_health']}")
    print(f"Sustainability Tip: {info['tip']}")

# Plot the distribution of the target labels
plt.figure(figsize=(15, 6))
sns.countplot(data=df, x='label', palette='tab20')
plt.xticks(rotation=90)
plt.title('Distribution of Crops in Dataset (SDG 2: Data Balance)')
plt.xlabel('Crop Type')
plt.ylabel('Count')
plt.show()

# Nutrient distribution for top 5 crops for better clarity
top_crops = df['label'].unique()[:5]
df_subset = df[df['label'].isin(top_crops)]

fig, ax = plt.subplots(1, 3, figsize=(18, 6))

# Nitrogen Distribution
sns.boxplot(x='label', y='N', data=df_subset, ax=ax[0], palette='Set2')
ax[0].set_title('Nitrogen (N) Requirements')

# Phosphorus Distribution
sns.boxplot(x='label', y='P', data=df_subset, ax=ax[1], palette='Set2')
ax[1].set_title('Phosphorus (P) Requirements')

# Potassium Distribution
sns.boxplot(x='label', y='K', data=df_subset, ax=ax[2], palette='Set2')
ax[2].set_title('Potassium (K) Requirements')

plt.tight_layout()
plt.show()

# Analyzing rainfall requirements across different crops
plt.figure(figsize=(15, 8))
sns.barplot(x='label', y='rainfall', data=df, palette='coolwarm')
plt.xticks(rotation=90)
plt.title('Average Rainfall Requirement by Crop (SDG 13: Water Management)')
plt.xlabel('Crop Name')
plt.ylabel('Rainfall (mm)')
plt.show()

# Scatter plot to show the relationship between Temperature and Humidity for specific crops
# Focusing on rice and maize for comparison
crops_to_compare = df[df['label'].isin(['rice', 'maize', 'coffee'])]

plt.figure(figsize=(10, 8))
sns.scatterplot(data=crops_to_compare, x='temperature', y='humidity', hue='label', s=100, alpha=0.7)
plt.title('Climate Clusters: Humidity vs. Temperature (Pattern Detection)')
plt.grid(True, linestyle='--', alpha=0.6)
plt.show()